// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(

)
// LIBRARY_DEPENDENCIES_HASH 509c57ce2ddc07e180838ca1b059056099003283
