// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "ch.qos.logback" % "logback-classic" % "1.2.2",
  "ch.qos.logback" % "logback-core" % "1.2.2",
  "com.chuusai" % "shapeless_2.12" % "2.3.2",
  "com.github.melrief" % "pureconfig_2.12" % "0.6.0",
  "com.github.mpilquist" % "simulacrum_2.12" % "0.10.0",
  "com.typesafe" % "config" % "1.3.1",
  "com.typesafe.scala-logging" % "scala-logging_2.12" % "3.5.0",
  "io.monix" % "monix-cats_2.12" % "2.2.3",
  "io.monix" % "monix-eval_2.12" % "2.2.3",
  "io.monix" % "monix-execution_2.12" % "2.2.3",
  "io.monix" % "monix-reactive_2.12" % "2.2.3",
  "io.monix" % "monix-types_2.12" % "2.2.3",
  "org.jctools" % "jctools-core" % "2.0",
  "org.reactivestreams" % "reactive-streams" % "1.0.0",
  "org.scala-sbt" % "test-interface" % "1.0",
  "org.scalacheck" % "scalacheck_2.12" % "1.13.4",
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "org.typelevel" % "catalysts-macros_2.12" % "0.0.5",
  "org.typelevel" % "catalysts-platform_2.12" % "0.0.5",
  "org.typelevel" % "cats-core_2.12" % "0.9.0",
  "org.typelevel" % "cats-free_2.12" % "0.9.0",
  "org.typelevel" % "cats-jvm_2.12" % "0.9.0",
  "org.typelevel" % "cats-kernel-laws_2.12" % "0.9.0",
  "org.typelevel" % "cats-kernel_2.12" % "0.9.0",
  "org.typelevel" % "cats-laws_2.12" % "0.9.0",
  "org.typelevel" % "cats-macros_2.12" % "0.9.0",
  "org.typelevel" % "cats_2.12" % "0.9.0",
  "org.typelevel" % "discipline_2.12" % "0.7.2",
  "org.typelevel" % "machinist_2.12" % "0.6.1",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH 69a878ad3fd36bac6fbf72c023d985299d84cc8f
