// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.chuusai" % "shapeless_2.12" % "2.3.2",
  "com.github.mpilquist" % "simulacrum_2.12" % "0.10.0",
  "io.circe" % "circe-core_2.12" % "0.7.0",
  "io.circe" % "circe-generic_2.12" % "0.7.0",
  "io.circe" % "circe-numbers_2.12" % "0.7.0",
  "org.typelevel" % "cats-core_2.12" % "0.9.0",
  "org.typelevel" % "cats-kernel_2.12" % "0.9.0",
  "org.typelevel" % "cats-macros_2.12" % "0.9.0",
  "org.typelevel" % "machinist_2.12" % "0.6.1",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH 8e1153314c053d821ba45483148ddc163327593e
